### ISSUE TITLE
在桌面无法使用

### ISSUE THREAD

**Issue by izhengzhixian** [luckytianyiyan/TyLauncher#1]
win7 64位旗舰版
当在桌面右键刷新以后，用快捷键弹出本软件窗口，没有聚焦到本窗口。然后比如说按A键，这时候就会在桌面找到A开头的文件。
PS：英文不好，只能用中文了，请见谅。

**Comment by ty0x2333** [comment]
@zzx666 这个项目我已经停止维护了. 因为我已经不再在Windows下开发了.

你可以尝试修复它, 并提交 Pull Request 来贡献代码.
